create database bancodb;

use bancodb;

CREATE TABLE TYPE_CUSTOMER (
	ID_TYPE_CUSTOMER INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(11) NOT NULL,
	PRIMARY KEY (ID_TYPE_CUSTOMER)
);

INSERT INTO TYPE_CUSTOMER (NAME) VALUES ('PERSONAL');
INSERT INTO TYPE_CUSTOMER (NAME) VALUES ('EMPRESARIAL');

CREATE TABLE CUSTOMER (
	ID_CUSTOMER INT NOT NULL AUTO_INCREMENT,
	ID_TYPE_CUSTOMER INT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	GENDER CHAR(1) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	TYPE_DOCUMENT VARCHAR(30) NOT NULL,
	NUMBER_DOCUMENT VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(100),
	PRIMARY KEY (ID_CUSTOMER),
	FOREIGN KEY (ID_TYPE_CUSTOMER) REFERENCES TYPE_CUSTOMER(ID_TYPE_CUSTOMER)
);

INSERT INTO CUSTOMER ( ID_TYPE_CUSTOMER, NAME, LAST_NAME, GENDER, EMAIL, TYPE_DOCUMENT, NUMBER_DOCUMENT, ADDRESS) VALUES('1', 'Juan', 'Lopez', 'M', 'juan@gmail.com', '1', '12345678', 'Av. Separadora Industrial 39');
INSERT INTO CUSTOMER ( ID_TYPE_CUSTOMER, NAME, LAST_NAME, GENDER, EMAIL, TYPE_DOCUMENT, NUMBER_DOCUMENT, ADDRESS) VALUES('2', 'Pedro', 'Mejia', 'M', 'pedri@gmail.com', '1', '999999', 'Av. Javier Prado 557');
INSERT INTO CUSTOMER ( ID_TYPE_CUSTOMER, NAME, LAST_NAME, GENDER, EMAIL, TYPE_DOCUMENT, NUMBER_DOCUMENT, ADDRESS) VALUES('1', 'Alan', 'Castillo', 'M', 'alancas@gmail.com', '1', '8635888', 'Av. Miraflores 123');

CREATE TABLE TYPE_PRODUCT (
	ID_TYPE_PRODUCT INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(6) NOT NULL,
    PRIMARY KEY (ID_TYPE_PRODUCT)
);

INSERT INTO TYPE_PRODUCT (NAME) VALUES ('Activo');
INSERT INTO TYPE_PRODUCT (NAME) VALUES ('Pasivo');


CREATE TABLE PRODUCT (
	ID_PRODUCT INT NOT NULL AUTO_INCREMENT,
    ID_TYPE_PRODUCT INT NOT NULL,
	NAME VARCHAR(100),
	COMMISSION DECIMAL(5,2) NOT NULL,
	LIMIT_MAXIMUM INT,
	PRIMARY KEY (ID_PRODUCT),
	FOREIGN KEY (ID_TYPE_PRODUCT) REFERENCES TYPE_PRODUCT (ID_TYPE_PRODUCT)
);

INSERT INTO PRODUCT (ID_TYPE_PRODUCT, NAME, COMMISSION, LIMIT_MAXIMUM) VALUES ( 2, 'Ahorro', 0, 5);
INSERT INTO PRODUCT (ID_TYPE_PRODUCT, NAME, COMMISSION, LIMIT_MAXIMUM) VALUES ( 2, 'Cuenta corriente', 100.00, 0);
INSERT INTO PRODUCT (ID_TYPE_PRODUCT, NAME, COMMISSION, LIMIT_MAXIMUM) VALUES ( 2, 'Plazo fijo', 0, 1);

CREATE TABLE ACCOUNT (
	ID_ACCOUNT INT NOT NULL AUTO_INCREMENT,
	ID_CUSTOMER INT NOT NULL,
	ID_PRODUCT INT NOT NULL,
	NUMBER VARCHAR(20),
    BALANCE DECIMAL(10,2) NOT NULL,
    MONEY VARCHAR(50) NOT NULL,
    ISO_MONEY VARCHAR(3) NOT NULL,
    PRIMARY KEY (ID_ACCOUNT),
	FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER (ID_CUSTOMER),
	FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

INSERT INTO ACCOUNT (ID_CUSTOMER, ID_PRODUCT, NUMBER, BALANCE, MONEY, ISO_MONEY) VALUES (1,'1','5876324586325955', 100, 'Nuevo Sol', 'PEN');
INSERT INTO ACCOUNT (ID_CUSTOMER, ID_PRODUCT, NUMBER, BALANCE, MONEY, ISO_MONEY) VALUES (2,'2','9866324586325955', 200, 'Nuevo Sol', 'PEN');
INSERT INTO ACCOUNT (ID_CUSTOMER, ID_PRODUCT, NUMBER, BALANCE, MONEY, ISO_MONEY) VALUES (3,'1','0006324586325955', 150, 'Nuevo Sol', 'PEN');

CREATE TABLE LOAN (
	ID_LOAN INT NOT NULL AUTO_INCREMENT,
	ID_CUSTOMER INT NOT NULL,
    ID_TYPE_PRODUCT INT NOT NULL,
	REASON VARCHAR(50),
	AMOUNT DECIMAL(10,2) NOT NULL,
	RATE DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (ID_LOAN),
	FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER (ID_CUSTOMER),
	FOREIGN KEY (ID_TYPE_PRODUCT) REFERENCES TYPE_PRODUCT (ID_TYPE_PRODUCT)
);

INSERT INTO LOAN (ID_CUSTOMER, ID_TYPE_PRODUCT, REASON, AMOUNT, RATE) VALUES (2, 1, 'CONSTRUCCION DE INMUEBLE', 100000.00 , 18.00);

CREATE TABLE CARD (
	ID_CARD INT NOT NULL AUTO_INCREMENT,
	ID_CUSTOMER INT NOT NULL,
    ID_TYPE_PRODUCT INT NOT NULL,
	NUMBER VARCHAR(20),
	LIMIT_CARD DECIMAL(8,2) NOT NULL,
    PRIMARY KEY (ID_CARD),
	FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER (ID_CUSTOMER),
	FOREIGN KEY (ID_TYPE_PRODUCT) REFERENCES TYPE_PRODUCT (ID_TYPE_PRODUCT)
);

INSERT INTO CARD(ID_CUSTOMER, ID_TYPE_PRODUCT, NUMBER, LIMIT_CARD) VALUES (3, 1, '12345678901234567890', 10000.00);
INSERT INTO CARD(ID_CUSTOMER, ID_TYPE_PRODUCT, NUMBER, LIMIT_CARD) VALUES (2, 1, '12345678901234567880', 90000.00);

CREATE TABLE TYPE_MOVEMENT (
	ID_TYPE_MOVEMENT INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(8),
    PRIMARY KEY (ID_TYPE_MOVEMENT)
);

INSERT INTO TYPE_MOVEMENT (NAME) VALUES ('Deposito');
INSERT INTO TYPE_MOVEMENT (NAME) VALUES ('Retiro');

CREATE TABLE MOVEMENT (
	ID_MOVEMENT INT NOT NULL AUTO_INCREMENT,
    ID_TYPE_MOVEMENT INT NOT NULL,
	ID_ACCOUNT INT NOT NULL,
	AMOUNT DECIMAL(8,2) NOT NULL,
	DATE_REGISTRATION DATETIME NOT NULL,
    PRIMARY KEY (ID_MOVEMENT),
	FOREIGN KEY (ID_TYPE_MOVEMENT) REFERENCES TYPE_MOVEMENT (ID_TYPE_MOVEMENT),
	FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID_ACCOUNT)
);

INSERT INTO MOVEMENT (ID_TYPE_MOVEMENT, ID_ACCOUNT, AMOUNT, DATE_REGISTRATION) VALUES (1, 1, 100.00, now());
INSERT INTO MOVEMENT (ID_TYPE_MOVEMENT, ID_ACCOUNT, AMOUNT, DATE_REGISTRATION) VALUES (2, 1, 30.00, now());
INSERT INTO MOVEMENT (ID_TYPE_MOVEMENT, ID_ACCOUNT, AMOUNT, DATE_REGISTRATION) VALUES (1, 1, 150.00, now());
INSERT INTO MOVEMENT (ID_TYPE_MOVEMENT, ID_ACCOUNT, AMOUNT, DATE_REGISTRATION) VALUES (1, 1, 10.00, now());
INSERT INTO MOVEMENT (ID_TYPE_MOVEMENT, ID_ACCOUNT, AMOUNT, DATE_REGISTRATION) VALUES (1, 1, 20.00, now());
INSERT INTO MOVEMENT (ID_TYPE_MOVEMENT, ID_ACCOUNT, AMOUNT, DATE_REGISTRATION) VALUES (2, 1, 80.00, now());

CREATE TABLE TYPE_SERVICE (
	ID_TYPE_SERVICE INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
    PRIMARY KEY (ID_TYPE_SERVICE)
);

INSERT INTO TYPE_SERVICE (NAME) VALUES ('Intenet');

CREATE TABLE SERVICE (
	ID_SERVICE INT NOT NULL AUTO_INCREMENT,
	ID_TYPE_SERVICE INT NOT NULL,
	NAME VARCHAR(100),
    PRIMARY KEY (ID_SERVICE),
	FOREIGN KEY (ID_TYPE_SERVICE) REFERENCES TYPE_SERVICE (ID_TYPE_SERVICE)
);

INSERT INTO SERVICE (ID_TYPE_SERVICE, NAME) VALUES (1, 'Movistar');
INSERT INTO SERVICE (ID_TYPE_SERVICE, NAME) VALUES (1, 'Claro');
INSERT INTO SERVICE (ID_TYPE_SERVICE, NAME) VALUES (1, 'Entel');

CREATE TABLE TYPE_TRANSACTION (
	ID_TYPE_TRANSACTION INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
    PRIMARY KEY (ID_TYPE_TRANSACTION)
);

INSERT INTO TYPE_TRANSACTION (NAME) VALUES ('Consumo');
INSERT INTO TYPE_TRANSACTION (NAME) VALUES ('Pago');

CREATE TABLE TRANSACTION (
	ID_TRANSACTION INT NOT NULL AUTO_INCREMENT,
	ID_TYPE_TRANSACTION INT NOT NULL,
    ID_CARD INT,
    ID_LOAN INT,
	AMOUNT DECIMAL(8,2) NOT NULL,
	DATE_REGISTRATION  DATETIME NOT NULL,
    PRIMARY KEY (ID_TRANSACTION),
	FOREIGN KEY (ID_TYPE_TRANSACTION) REFERENCES TYPE_TRANSACTION (ID_TYPE_TRANSACTION),
	FOREIGN KEY (ID_CARD) REFERENCES CARD (ID_CARD),
	FOREIGN KEY (ID_LOAN) REFERENCES LOAN (ID_LOAN)
);

INSERT INTO TRANSACTION (ID_TYPE_TRANSACTION, ID_CARD, AMOUNT, DATE_REGISTRATION) VALUES (1, 1, 39.90, now());
INSERT INTO TRANSACTION (ID_TYPE_TRANSACTION, ID_LOAN, AMOUNT, DATE_REGISTRATION) VALUES (2, 1, 79.90, now());

CREATE TABLE TRANSACTION_CONSUMPTION (
	ID_TRANSACTION_CONSUMPTION INT NOT NULL AUTO_INCREMENT,
    ID_TRANSACTION INT NOT NULL,
    ID_SERVICE INT NOT NULL,
    PRIMARY KEY (ID_TRANSACTION_CONSUMPTION),
	FOREIGN KEY (ID_TRANSACTION) REFERENCES TRANSACTION (ID_TRANSACTION),
	FOREIGN KEY (ID_SERVICE) REFERENCES SERVICE (ID_SERVICE)
)
